/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/3dmodels/sqysh.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Sqysh(props) {
  const { nodes, materials } = useGLTF('/3dmodels/sqysh.glb')
  const modelRef = useRef()

  // useFrame(() => {
  //   if (modelRef.current) {
  //     modelRef.current.rotation.y += 0.05 // Adjust the speed of rotation
  //   }
  // })
  return (
    <group ref={modelRef} {...props} dispose={null} scale={[4, 4, 4]}>
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
    </group>
  )
}

useGLTF.preload('/3dmodels/sqysh.glb')
